#pragma kernel CSVoxelizer

#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Voxelizer/VoxelGeneratorStart.cginc"

Voxel GetVoxelAt(float3 position) {
	Voxel voxel;

	// Density value for biome 1
	float density = -fbmCellular(position.xz * 0.001, 6, 0.49, 2.1).x * 60;
	voxel.density = density + position.y;

	voxel.material = 0;
	return voxel;
}

#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Voxelizer/VoxelGeneratorEnd.cginc"