#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/common.cginc"
#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/cellular2D.cginc"
#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/cellular3D.cginc"
#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/erosion.cginc"
#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/noise2D.cginc"
#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/noise3D.cginc"
#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/fbm.cginc"
#include "Packages/com.jedjoud.voxelterraingenerator/Runtime/Utils/noises/voronoise.cginc"